blank_issues_enabled: false
contact_links:
  - name: Preciso de ajuda com a Loritta!
    url: https://loritta.website/br/support
    about: Visite o nosso servidor de suporte para conseguir ajuda!
  - name: Quero ser desbanido!
    url: https://youtu.be/dQw4w9WgXcQ
    about: 🤷
