name: Auto React

on:
  issue_comment:
    types: [created]

jobs:
  issue_created:
    # This job only runs for issue comments
    name: Issue created
    if: ${{ !github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Comment on issue #${{ github.event.issue.number }}"